### ISSUE TITLE
Does not build on Mac OS X 10.6.2

### ISSUE THREAD

**Issue by chrigi** [wikireader/wikireader#11]
The readlink binary shipped with Mac OS X 10.6 is not the same as the linux one, so "readlink -m" will not work.
After installing the coreutilities through macports and changing the the file to "greadlink -m" it proceeded but said that the installed gcc was not able to produce executable binaries. Latest Xcode is installed.

**Comment by vandys** [comment]
Well, you could build it from source from ctan.  But... this bug is from like 10 years ago.  Your interest might have waned! :)  Sorry it didn't work out.
