### ISSUE TITLE
Request clarification on RS-232 console

### ISSUE THREAD

**Issue by vandys** [wikireader/wikireader#55]
Under the hardware section, could somebody add some specifics on the console access?
I know from the curent docs about the debug connector, and about TXD/RXD.  But there's
no GND pin, so which other pin should I use as the ground reference for the RS-232?

Their levels are, I assume, 3.3v TTL?  Is it OK to directly connect a 3.3v TTL UART, or are
there any other buffering considerations?

Thanks much!

**Comment by hxw** [comment]
Added the following text to the RDd/TXD description:

These pins are directly connected to CPU and are 3.3V signals with respect to the VSS pin. **Important Note** When using a USB to serial cable ensure that it is 3.3V (like the ones for Raspberry Pi); only connect RXD/TXD and VSS(GND) signals **Do NOT** connect VCC as this is usually 5V and will cause damage to the WikiReader.

**Comment by vandys** [comment]
Awesome.  I'm going to devote one to permanently soldered power/console, and that's all the
details I could hope for.  Thanks much!
