### ISSUE TITLE
init.app autoboot

### ISSUE THREAD

**Issue by vandys** [wikireader/wikireader#56]
init.app can offer a menu, but it looks like it never will if called with autoboot--but that's hard-coded
in the kernel.  So we can't change init.app's behavior without a kernel change?

Would you consider accepting a patch to tell init.app to go ahead and always menu its apps?

**Comment by hxw** [comment]
Maybe a better change is to have init.c: bool ReadCommands(const char *filename) return int,
If zero power off, if only one command in init.ini run that command,  otherwise(i.e. >1) display the menu.

**Comment by hxw** [comment]
d8d169d was committed to fix this
